M48
; DRILL file {KiCad (6.0.5)} date Mon Mar 13 10:12:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-13T10:12:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X5.025Y-3.2402
X5.025Y-5.13
X6.3243Y-3.2402
X6.3243Y-5.13
T0
M30
